//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheresButtons.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheresButtons.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Cinderella, where&apos;s Buttons?.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button control clicked handler called..
        /// </summary>
        internal static string ButtonClickHappened {
            get {
                return ResourceManager.GetString("ButtonClickHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomControl tap gesture recognised..
        /// </summary>
        internal static string CustomControlTapHappened {
            get {
                return ResourceManager.GetString("CustomControlTapHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Cinderella, where&apos;s Buttons?.
        /// </summary>
        internal static string MainPageHeading {
            get {
                return ResourceManager.GetString("MainPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app demonstrates how UI elements that are not built using appropriate semantic controls can result in the app being unusable for many people. For example, two of the tappable UI elements showing face emojis below cannot be used by people who use their voice to interact with apps on iOS, nor by people who use their keyboards to interact with apps on Windows.
        ///
        ///The app is built only to demonstrate that one point, and is not intended to be a usable app. For example, the tappable elements provide no visua [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainPageInstructions {
            get {
                return ResourceManager.GetString("MainPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this app&apos;s ReadMe at Github.
        /// </summary>
        internal static string OpenGithubReadMe {
            get {
                return ResourceManager.GetString("OpenGithubReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate good.
        /// </summary>
        internal static string RateGood {
            get {
                return ResourceManager.GetString("RateGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate great.
        /// </summary>
        internal static string RateGreat {
            get {
                return ResourceManager.GetString("RateGreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate poor.
        /// </summary>
        internal static string RatePoor {
            get {
                return ResourceManager.GetString("RatePoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate terrible.
        /// </summary>
        internal static string RateTerrible {
            get {
                return ResourceManager.GetString("RateTerrible", resourceCulture);
            }
        }
    }
}
